// Compatibility re-export of the shared executable schema.
// The sole source of truth lives in `shared/src/artifact-schema.ts`.
export {
  ARTIFACT_NODE_TYPES,
  ARTIFACT_SLUG_MAX_LENGTH,
  ARTIFACT_SPEC_RESOURCE_LIMITS,
  ArtifactNodeSchema,
  ArtifactResourceError,
  ArtifactSizeError,
  ArtifactSlugSchema,
  ArtifactValidationError,
  MAX_AGGREGATE_FILE_SOURCE_BYTES,
  MAX_DATASETS,
  MAX_FILE_SOURCE_BYTES,
  MAX_FILE_TREE_DEPTH,
  MAX_FILE_TREE_ITEMS,
  MAX_NODE_DEPTH,
  MAX_TOP_LEVEL_NODES,
  MAX_TOTAL_NODES,
  RAW_ARTIFACT_MAX_BYTES,
  VisualArtifactSpecSchema,
  parseRawArtifactJson,
  parseVisualArtifactSpec,
  preflightArtifactSpec,
  safeParseVisualArtifactSpec,
  type ArtifactColumn,
  type ArtifactFlowItem,
  type ArtifactNode,
  type ArtifactPreflightResult,
  type ArtifactSpecResourceLimits,
  type ArtifactTone,
  type VisualArtifactSpec,
} from "@agents/visual-artifact-annotations/contract"
